version: '3'

services:
  mysql:
    build: .
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demo

volumes:
  mysql-data: